name: golangci
on:
  pull_request:
    paths:
      - "**.go"
      - .github/workflows/golangci.yml

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          key: ${{ runner.os }}-golangci-${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"
      # - name: Cache Go build and module
      #   id: cache
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cache/go-build
      #       ~/go/pkg/mod
      #     key: ${{ runner.os }}-golangci-${{ hashFiles('./go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-golangci-
